# Generated by Django 6.0.4 on 2026-04-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_at',
            new_name='created_at',
        ),
    ]
